### ISSUE TITLE
(╯°□°）╯︵ ┻━┻

### ISSUE THREAD

**Issue by danshevluk** [iridakos/table_flipper#3]
(╯°□°）╯︵ ┻━┻

**Comment by dankimio** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by tlatsas** [comment]
┬─┬ノ( º _ ºノ)

**Comment by iridakos** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by NULL-OPERATOR** [comment]
(☞ﾟ∀ﾟ)☞  _:･ﾟ✧_･ﾟ  ┬─┬

**Comment by danshevluk** [comment]
@NULL-OPERATOR Wow! Your magic seems to work fine :sparkles: Table is OK now ┬─┬

**Comment by isexcats** [comment]
fuck my boy cunt this is a shitty thread
